version: '3'
services:
  server:
    container_name: dev_api
    working_dir: /code
    ports: 
      - 3000:3000
    environment: 
      - PORT= 3000
    depends_on:
      - db
    command: bash -c "npm install && npm start"

  db:
    container_name: dev_db
    volumes:
      - "dbdata:/var/lib/mongodb/data"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mustard
      - MONGO_INITDB_DATABASE=quizzlybears
      - MONGO_INITDB_ROOT_PASSWORD=marywilkes
volumes:
  dbdata:
networks: 
  default:
    name: app_dev
